name: Building Program
run-name: Building ${{ GITHUB.REPOSITORY }}

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  sid:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-sid.yml@master
    secrets: inherit

  tianlu-bpo:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-backport.yml@master
    secrets: inherit

  meimei:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-meimei.yml@master
    secrets: inherit